version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: danhsachcho_app
    ports:
      - "3002:3002"
    networks:
      - hospital_net
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    volumes:
      - ./logs:/app/logs
      - ./public/audio/cache:/app/public/audio/cache
    restart: unless-stopped

networks:
  hospital_net:
    external: true
