version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: danhsachcho_app
    ports:
      - "3002:3002"
    networks:
      - hospital_net
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3002
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=3002
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./logs:/app/logs
      - ./wwwroot/audio/cache:/app/wwwroot/audio/cache
    restart: unless-stopped

networks:
  hospital_net:
    external: true
